### ISSUE TITLE
Time played box is cut off

### ISSUE THREAD

**Issue by Pixxel123** [TheKersalMassive/ReskinPS5#2]
I've noticed that the time played box is slightly cut off at my resolution of 1920 x 1080 at 150% scaling (using on a TV screen). Here's a screenshot:

![image](https://user-images.githubusercontent.com/36304206/138354731-121e4c4b-069d-4544-a985-1a8d126a23f4.png)

**Comment by TheKersalMassive** [comment]
I am not sure if it's caused by this or scaling related (as I can't reproduce it at 1080p @ 150% scaling), but I have corrected the Grid Row allocations in **GameDetails.xaml** which may have been causing this issue.

Are you able to edit the GameDetails.xaml file in the Views folder under line 24 and change:

`<RowDefinition Height="7*" />`
to 
`<RowDefinition Height="6*" />`

And confirm if this fixes it for you? As I can't reproduce it on a 1080p display myself.

**Comment by Pixxel123** [comment]
The issue still remains unfortunately. Do I need to do anything else other than edit the GameDetails.xaml file and restart Playnite?
